import Header from './header';
import Footer from './footer';

export const metadata = {
  title: "Following Codevolution's Next.js 15 YT tutorial",
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

